Clean UI, add some basic visualization features
netsys-lab/scion-browser-extensions pull request #12
Opened 2021-10-23 11:49 UTC by martenwallewein

Fix icons, add some css to popup, visualize running extension and active forwarding

2021-10-28 07:34 UTC, JordiSubira requested changes

2021-10-28 07:34 UTC, JordiSubira commented on chrome/popup.js
>  'use strict';
Not sure, but we might need the Copyright header in every file

2021-10-28 07:34 UTC, JordiSubira commented on chrome/popup.js
> +  });
I think here (or in `function handleTabChange(tab)` in background.js), if the toggle is unchecked we should update the headline.innerText to Inactive. Otherwise, its value is never changed, even if the tab changes.

2021-10-28 07:34 UTC, JordiSubira commented on chrome/background.js
>    // Receive message from popup.js when adding or removing hostname
Could you please remove this obsolete comment? I forgot to do it.

2021-11-01 15:24 UTC, martenwallewein commented on chrome/popup.js
>  'use strict';
Good Point

2021-11-01 15:28 UTC, martenwallewein commented on chrome/popup.js
> +  });
Sounds good

2021-11-01 15:28 UTC, martenwallewein commented on chrome/background.js
>    // Receive message from popup.js when adding or removing hostname
Sure

2021-11-03 16:48 UTC, JordiSubira approved these changes

2021-11-03 16:55 UTC, merged